version: "3"

services:
    mysql:
        container_name: laravel
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "helloworld"
            MYSQL_DATABASE: "laravel"
        ports:
            - "3306:3306"

    adminer:
        container_name: admin
        image: adminer
        ports:
            - 8080:8080
